config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :attendance
  end
  
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "events#index"

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
  	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :admin, foreign_key: 'admin_id', class_name: 'User'	
	has_many :attendances
    has_many :users, through: :attendances
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: 'admin_id', class_name: "Event"
  has_many :attendances
  has_many :events, through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
    @@event = 0
    
    def show
        @event = Event.find(params[:event_id])
        @admin = User.find(@event.admin_id)
    end

    def new
    @@event = params[:event_id]    
    end

    def create
        Attendance.create(user_id: current_user.id, event_id: @@event, stripe_customer_id: params[:stripe_customer_id])
    end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

    def create
    @total = params[:total].to_d
    StripeId.new.store(params[:event])
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'eur',
            unit_amount: (@total*100).to_i,
            product_data: {
                name: 'Rails Stripe Checkout', 
            },
          },
          quantity: 1
        },
      ],
      mode: 'payment',
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
    redirect_to @session.url, allow_other_host: true
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    StripeId.new.create(current_user.id)
  end

  def cancel
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    event = params[:event]
    @event = Event.new(title: event[:title], 
      		description: event[:description],
      		location: event[:location],
      		price: event[:price],
      		start_date: event[:start_date],
      		duration: event[:duration],
          admin: current_user)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
        puts "gg"
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
        puts "bouh"
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/attendance/new.html.erb
<%= button_to "Passer commande !", checkout_create_path(total: Event.find(params[:event_id]).price), params: { event: params[:event_id]}, class: "btn btn-primary", remote: true %>

app/views/attendance/show.html.erb
<%= @event.title %>

app/views/checkout/cancel.html.erb
Echec
Le paiement n'a pas abouti.

app/views/checkout/success.html.erb
Succès
Nous avons bien reçu votre paiement de <%= number_to_currency(@payment_intent.amount_received / 100.0, unit: "€", separator: ",", delimiter: "", format: "%n %u") %>.
Le statut de votre paiement est : <%= @payment_intent.status %>.

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Start date:</strong>
    <%= event.start_date %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= event.duration %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= event.price %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= event.location %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.datetime_field :start_date %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<h1>Events</h1>

<div id="events">
  <% @events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
  <% end %>
</div>

	<% if user_signed_in? %>
  		<%= link_to "New event", new_event_path %>
	<% else %>
  		<p>t'es beau</p>
	<% end %>

app/views/events/new.html.erb
<h1>New event</h1>
<% if user_signed_in? %>
  <div class="text-center" style="padding: 15px">
  <div class="form-signin w-50 m-auto">
    <%= form_for(:event, url: events_path, html: { method: :post }) do |f| %>

      <div class="form-group">
        <%= f.label 'Date de début:' %><br/>
        <%= f.datetime_field :start_date, autofocus: true, autocomplete: "start_date", placeholder: "Date de début de l'événement", class: 'form-control text-center' %>
      </div><br/>

      <div class="form-group">
        <%= f.label 'Durée (en minute):' %><br/>
        <%= f.number_field :duration, step: 5, autofocus: true, autocomplete: "duration", placeholder: "Durée de l'événement", class: 'form-control text-center' %>
      </div><br/>

      <div class="form-group">
        <%= f.label 'Titre:' %><br/>
        <%= f.text_field :title, autofocus: true, autocomplete: "title", placeholder: "Titre", class: 'form-control text-center' %>
      </div><br/>

      <div class="form-group">
        <%= f.label 'Description:' %><br/>
        <%= f.text_field :description, autofocus: true, autocomplete: "description", placeholder: "Description", class: 'form-control text-center' %>
      </div><br/>

      <div class="form-group">
        <%= f.label 'Prix:' %><br/>
        <%= f.number_field :price, in: 1..1000, step: 1, autofocus: true, autocomplete: "price", placeholder: "Prix par personne", class: 'form-control text-center' %>
      </div><br/>

      <div class="form-group">
        <%= f.label 'Lieu:' %><br/>
        <%= f.text_field :location, autofocus: true, autocomplete: "location", placeholder: "Lieu  de l'événement", class: 'form-control text-center' %>
      </div><br/>

      <div class="actions">
        <%= f.submit "Créer l'événement", class: 'w-100 btn btn-lg btn-primary' %>
      </div><br/>
    <% end %>
  </div>
</div>
<% else %>
  <p>t'es encore plus beau</p>
<% end %>

app/views/events/show.html.erb
<%= render @event %>

<div>
  <%= link_to "Edit this event", edit_event_path(@event) %> |
  <%= link_to "Back to events", events_path %><br/><br/>

  <%= button_to "Destroy this event", @event, method: :delete %><br/>

  <%= button_to "Rejoindre l'event", new_event_attendance_path(@event.id), method: :get %>

  Nombre de participant(s) : <%= @event.users.count %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Logitech</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
  
<nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Logo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>

            <% if user_signed_in? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="/" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Mes informations
                </a>
                <ul class="dropdown-menu">
                  <li><p class="dropdown-item">Email : <%= current_user.email %></p></li>
                  <li><%= link_to "Edit email / password", edit_user_registration_path, class: "dropdown-item" %></li>
                </ul>
              </li>

              <li class="nav-item">
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link active" %>
              </li>

            <% else %>
              <li class="nav-item">    
                <%= link_to "Sign in", new_user_session_path, class: "nav-link active" %>
              </li>

              <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, class: "nav-link active" %>
              </li>

            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>

</html>